import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — ResumeRank AI",
  description: "The terms and conditions governing your use of ResumeRank AI.",
};

const SECTIONS = [
  {
    title: "1. Acceptance of terms",
    body: "By creating an account or using ResumeRank AI (the 'Service'), you agree to these Terms of Service. If you do not agree, do not use the Service.",
  },
  {
    title: "2. The service",
    body: "ResumeRank AI provides AI-powered resume analysis, scoring, and rewriting against job descriptions you supply. The Service is provided as-is and the analysis is advisory only — you remain responsible for your own resume and job applications.",
  },
  {
    title: "3. Accounts",
    body: "You are responsible for the security of your account credentials and for all activity that occurs under your account. Notify us immediately of any unauthorised use.",
  },
  {
    title: "4. Subscriptions and billing",
    body: "Paid plans (Pro, Team) are billed monthly or annually via Stripe. You can cancel at any time from the billing page; cancellation takes effect at the end of the current billing period. We do not provide refunds for partial periods except where required by law.",
  },
  {
    title: "5. Acceptable use",
    body: "You agree not to (a) upload content you do not have the right to share, (b) attempt to reverse-engineer, scrape, or otherwise abuse the Service, (c) use the Service to generate content that is unlawful, defamatory, or discriminatory, or (d) upload malicious files or attempt to disrupt the Service.",
  },
  {
    title: "6. Intellectual property",
    body: "You retain ownership of the resumes, job descriptions, and other content you upload. You grant us a limited licence to process that content solely to provide the Service. We retain ownership of the underlying models, software, and aggregated, anonymised usage analytics.",
  },
  {
    title: "7. AI-generated content",
    body: "Suggestions, scores, and rewrites are generated by an AI model and may contain errors. They are not a guarantee of employment or interview outcomes. Always review AI suggestions before applying them to your resume.",
  },
  {
    title: "8. Limitation of liability",
    body: "To the maximum extent permitted by law, ResumeRank AI is not liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability is limited to the amount you paid us in the twelve months preceding the claim.",
  },
  {
    title: "9. Termination",
    body: "We may suspend or terminate your account if you breach these Terms. You may delete your account at any time from the account settings page; deletion is permanent and removes your content.",
  },
  {
    title: "10. Changes to these terms",
    body: "We may update these Terms from time to time. Material changes will be communicated by email or in-app notice. Continued use after the effective date constitutes acceptance of the new terms.",
  },
  {
    title: "11. Governing law",
    body: "These Terms are governed by the laws of the jurisdiction in which ResumeRank AI is incorporated, without regard to conflict-of-law principles.",
  },
  {
    title: "12. Contact",
    body: "Questions about these Terms can be sent to legal@resumerank.ai.",
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background px-6 py-16">
      <div className="mx-auto max-w-3xl">
        <Link
          href="/"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← Back home
        </Link>
        <h1 className="mt-6 text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-muted-foreground">
          Last updated: 1 January 2026
        </p>
        <div className="prose prose-neutral mt-10 max-w-none dark:prose-invert">
          {SECTIONS.map((s) => (
            <section key={s.title} className="mt-8">
              <h2 className="text-xl font-semibold">{s.title}</h2>
              <p className="mt-2 text-muted-foreground">{s.body}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
